### ISSUE TITLE
Hyva 1.1.9

### ISSUE THREAD

**Issue by DHSServices** [ProxiBlue/hyva-proxiblue-multimenu#1]
Does this multimenu work on Hyva 1.1.9?
Hyva changed it menu templates from topmenu.phtml to 2 separate templates desktop.phtml and mobile.phtml.

**Comment by ProxiBlue** [comment]
Yes.

I have it on a site running on 1.1.9. Going live in a week.

**Comment by ProxiBlue** [comment]
This menu still uses topmenu.phtml https://github.com/ProxiBlue/hyva-proxiblue-multimenu/tree/main/src/view/frontend/templates/html/header, but is split between mobile and desktop in itself.

https://github.com/ProxiBlue/hyva-proxiblue-multimenu/tree/main/src/view/frontend/templates/html/header/topmenu

and is running fine on a 1.1.9 upgraded site as it replaces the hyva templates with own versions

Any issues, just file a bug, and we can make it work.

**Comment by ProxiBlue** [comment]
The multi menu is now compatible with 1.1.9 from version 1.3.0
