### ISSUE TITLE
Double clicking needed when trying to open second main category in mobile view

### ISSUE THREAD

**Issue by DHSServices** [ProxiBlue/hyva-proxiblue-multimenu#3]
In mobile view opening/closing a second main category requires double clicking/tapping. This only happens for main categories. When opening or closing a third main category, 2 clicks/taps are required as well. All browsers have this issue. See screen capture of opening and closing bug.
![double-clicking-needed](https://user-images.githubusercontent.com/70269551/148927932-4c9717c3-7f25-470d-b8e7-683f6aea4112.gif)

**Comment by ProxiBlue** [comment]
Hello,

updated version https://github.com/ProxiBlue/hyva-proxiblue-multimenu/releases/tag/1.3.1 fixed this issue

**Comment by ProxiBlue** [comment]
Ugh, no, seems when you go into mobile mode it happens, I just tested initially on a resized browser


https://user-images.githubusercontent.com/4994260/150267864-c3e34d34-71cd-4130-90b4-36fa55d9541c.mp4

**Comment by ProxiBlue** [comment]
Ok, fixed in 1.3.3


https://user-images.githubusercontent.com/4994260/150271038-295b10b2-2132-4488-8351-fbc1bf7a4531.mp4

**Comment by DHSServices** [comment]
Works perfect, Thank you very much Lucas!
