### ISSUE TITLE
Consider using Hyvä compatibility for CSS merging, instead of a separate file

### ISSUE THREAD

**Issue by GrimLink** [ProxiBlue/hyva-proxiblue-multimenu#6]
Currently this module is using a separate CSS file for handling the styling.

Consider adding the following things from the Hyvä docs https://docs.hyva.io/hyva-themes/compatibility-modules/tailwind-source-css-merging.html
So that the CSS is merged with the theme styling.

Or even beter inline all the styling in this module and use tailwind-config merging instead https://docs.hyva.io/hyva-themes/compatibility-modules/tailwind-config-merging.html

**Comment by ProxiBlue** [comment]
Hello,

css has been updated. Hyva did not support this when module was initially created, and never updated to support, plus tailwind 1 did not support transform or scale inline (but now does with the Hyva update to tailwind 3)

Not all css could be made inline. There seems to be an issue (or my lack for knowledge) with the group-hover on the elements as they are injected by code on rendering the child menus. Possible tailwind is not generating the needed styles as they are not inline on .phtml.

But, the css is now included as per Hyva inclusion, and massively simplified, as most could be moved inline now that tailwind supports transform and scale.

ref: https://github.com/ProxiBlue/hyva-proxiblue-multimenu/blob/1.4.0/src/view/frontend/tailwind/tailwind-source.css
